### ISSUE TITLE
Inconsistently locked GUI controls

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-template-source#23]
Among our templates the gui controls are "locked" inconsistently: some GUIs have all of them locked, some none, and rest are only partially locked.
EDIT: This is about **Locked** property that locks control position in the editor.

Expected: to have them consistently either locked or not locked throughout all the default GUI.

**Comment by morganwillcock** [comment]
I think I would have only set them as locked if it was required for the template to function, partly because it doesn't look very good as the locking effect is square. For the VerbCoin the locking is an option built into the module. Can you give some examples of the specific GUIs that are wrong?

**Comment by ivan-mogilko** [comment]
> partly because it doesn't look very good as the locking effect is square

By this you mean visually, or something else? I think locked property does not change the looks in game.

> Can you give some examples of the specific GUIs that are wrong?

Well, a random example is gExitGame in BASS template, it has Quit button locked but not Play button.

**Comment by morganwillcock** [comment]
Do you mean when the buttons are disabled? It is a square checkerboard effect so it doesn't look correct on any button that isn't square. But I don't know why it is only one button and not the other in the same GUI.

**Comment by ivan-mogilko** [comment]
Ah, seems like we are speaking of different things.

I mean, Locked property in the editor, that prevents from moving controls around.

**Comment by morganwillcock** [comment]
From memory I don't think I've knowingly set that, but yes that would be a bit strange to have some parts locked and others not, especially when if differs for controls that are in the foreground. I guess the question is, is it better to lock everything and have people go looking for the unlock controls, or to unlock everything and risk accidental movement, or to just lock anything that is deemed to be a lower layer?

For the purposes of learning how everything works, maybe having everything unlocked would be best so that no-one gets stuck looking for the unlock controls.

**Comment by ivan-mogilko** [comment]
> For the purposes of learning how everything works, maybe having everything unlocked would be best so that no-one gets stuck looking for the unlock controls.

Yes, I noticed this after a user asked why they cannot change the GUIs.

**Comment by ivan-mogilko** [comment]
Very well, I unlocked everything: 4de504ceeed6d1d322fd9b820937830f4c3082cb

It's easy to change to "lock all" too, may be done by a batch replace in Game.agf, because only GUI controls have "Locked" property left now.
